version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
  web:
    image: celcat-timetable-parser
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]